name: playwright-test

on: [push]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
             cd ./new-project
             npm ci
        
      - name: Install playwright browsers

        run: |
            ls -a
            cd ./new-project
            npx playwright install --with-deps
      
      - name: Install playwright
        run: |
            ls -a
            cd ./new-project
            npm install -D @playwright/test
        
      - name: Run tests
        run: |
            ls -a
            cd ./new-project
            ls -a
            npx playwright test
