name: playwright-test

on: 
  push:
  workflow_dispatch:
    
jobs:
  tests_e2e_playwright:
    name: Run end-to-end tests with playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
             cd ./playwright-test
             npm ci
      
      - name: Install playwright
        run: |
            cd ./playwright-test
            npm install -D @playwright/test
            npx playwright install --with-deps
        
      - name: Run tests
        run: |
            cd ./playwright-test
            npx playwright test

  test_e2e_testcafe:
    name: Run end-to-end test with test_e2e_testcafe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install testcafe dependencies
        run: |
             cd ./testcafe
             npm install -g testcafe
      - name: Run tests headless
        run: |
            cd ./testcafe/examples/basic
            testcafe "chrome:headless" test.js  