name: playwright-test

on: [push]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
             cd ./playwright-test/new-project/package.json
             npm ci
        
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run tests
        run: npx playwright test
